language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - COVERAGE_DEPS="php-coveralls/php-coveralls"

addons:
  mariadb: '10.4'

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env:
        - DEPS=latest
    - php: 7.2
      env:
        - DEPS=latest
    - php: 7.3
      env:
        - DEPS=latest
    - php: 7.4
      env:
        - DEPS=latest
    - php: 7.2
      env:
        - DEPS=latest
        - CS_CHECK=true
        - TEST_COVERAGE=true

before_install:
  - sudo mysql -u root --password="" < data/travis.sql
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs
  - if [[ $LEGACY_DEPS != '' ]]; then travis_retry composer update $COMPOSER_ARGS --with-dependencies $LEGACY_DEPS ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS ; fi
  - stty cols 120 && composer show

before_script:
  - chmod -R 777 /home/travis/build/OnePlc/PLC_X_User
  - cp /home/travis/build/OnePlc/PLC_X_User/vendor/oneplace/oneplace-core/config/autoload/local.php.dist /home/travis/build/OnePlc/PLC_X_User/vendor/oneplace/oneplace-core/config/autoload/local.php
  - cp /home/travis/build/OnePlc/PLC_X_User/vendor/oneplace/oneplace-core/config/autoload/global.php.dist /home/travis/build/OnePlc/PLC_X_User/vendor/oneplace/oneplace-core/config/autoload/global.php
  - mysql -u travis --password="" "travis" < /home/travis/build/OnePlc/PLC_X_User/vendor/oneplace/oneplace-core/module/Application/data/structure.sql
  - mysql -u travis --password="" "travis" < /home/travis/build/OnePlc/PLC_X_User/data/structure.sql
  - mysql -u travis --password="" "travis" < /home/travis/build/OnePlc/PLC_X_User/data/data.sql
  - mysql -u travis --password="" "travis" < /home/travis/build/OnePlc/PLC_X_User/vendor/oneplace/oneplace-core/module/Application/data/bootstrap.sql
  - mysql -u travis --password="" "travis" < /home/travis/build/OnePlc/PLC_X_User/vendor/oneplace/oneplace-core/module/Application/data/data.sql

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then vendor/bin/phpunit --coverage-clover ./clover.xml ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then vendor/bin/php-coveralls -v ; fi

notifications:
  email: false