<div class="row">
    <div class="col-md-4 py-4 px-4">
        <?=$this->partial('partial/usernav',[])?>
    </div>
    <div class="col-md-8 py-4 px-4">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title"><?=$this->translate('Profile')?></h3>
            </div>
            <div class="card-body">

            </div>
        </div>
    </div>
</div>
