<?php
use Application\Controller\CoreController;
?>
<div class="row">
    <div class="col-md-4 py-4 px-4">
        <?=$this->partial('partial/usernav',[])?>
    </div>
    <div class="col-md-8 py-4 px-4">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title"><?=$this->translate('Settings')?></h3>
            </div>
            <div class="card-body">
                <form action="" method="POST">
                    <div class="form-row">
                        <label for="input01" class="col-md-3 mb-3">
                            <?=$this->translate('Theme')?>
                        </label>
                        <div class="col-md-9 mb-3">
                            <?=CoreController::$oSession->oUser->getTheme()?> -
                            <a href="<?=$this->url('application',['action'=>'themes'])?>">
                                <?=$this->translate('Change theme')?>
                            </a>
                        </div>
                    </div>
                    <div class="form-row">
                        <label for="input01" class="col-md-3 mb-3">
                            <?=$this->translate('API')?>
                        </label>
                        <div class="col-md-9 mb-3">
                            <a href="<?=$this->url('user-api',['action'=>'manage'])?>">
                                <?=$this->translate('Manage API Keys')?>
                            </a>
                        </div>
                    </div>
                    <div class="form-row">
                        <label for="input01" class="col-md-3 mb-3">
                            <?=$this->translate('Updates')?>
                        </label>
                        <div class="col-md-9 mb-3">
                            <a href="<?=$this->url('application',['action'=>'checkforupdates'])?>">
                                <?=$this->translate('Check for Updates')?>
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
