<ul class="list-group">
<?php
# Get Partial Data
$aFieldsByForm = $this->aPartialData['aFields'];
$aUserFields = $this->aPartialData['aUserFields'];

# Print List with all Modules and Fields
foreach(array_keys($aFieldsByForm) as $sForm) {
    $oForm = $aFieldsByForm[$sForm]['oForm'];
    $aFields = $aFieldsByForm[$sForm]['aFields']; ?>
    <li class="list-group-item">
        <div class="row">
            <div class="col-md-2">
                <?=$oForm->label?>
            </div>
            <div class="col-md-2">
                <a href="#" class="btn btn-light plc-user-permissions-selectall">Select all</a>
                <a href="#" class="btn btn-light plc-user-permissions-unselectall">Unselect all</a>
            </div>
            <div class="col-md-8">
                <div class="row plc-user-permission-list">
                    <?php foreach($aFields as $oField) {
                        //var_dump($oField);
                        $bHasPerm = false;

                        if (array_key_exists($oForm->form_key,$aUserFields)) {
                            if (array_key_exists($oField->Field_ID,$aUserFields[$oForm->form_key])) {
                                $bHasPerm = true;
                            }
                        }
                        ?>
                        <div class="col-md-4">
                            <input type="checkbox"<?=($bHasPerm) ? ' checked' : ''?> name="<?=$this->sFormName?>-formfields[]" value="<?=$oField->Field_ID?>_<?=$oForm->form_key?>" />
                            <?=$oField->label?>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </li>
    <?php
}
?>
</ul>

