<ul class="list-group">
<?php
# Get Partial Data
$aFieldsByForm = $this->aPartialData['aFields'];
$aUserFields = $this->aPartialData['aUserFields'];

# Print List with all Modules and Fields
foreach(array_keys($aFieldsByForm) as $sForm) {
    $oForm = $aFieldsByForm[$sForm]['oForm'];
    $aFields = $aFieldsByForm[$sForm]['aFields']; ?>
    <li class="list-group-item">
        <div class="row">
            <div class="col-md-4"><?=$oForm->label?></div>
            <div class="col-md-8">
                <div class="row">
                    <?php foreach($aFields as $oField) {
                        //var_dump($oField);
                        $bHasPerm = false;

                        if(array_key_exists($oForm->form_key,$aUserFields)) {
                            if(array_key_exists($oField->Field_ID,$aUserFields[$oForm->form_key])) {
                                $bHasPerm = true;
                            }
                        }
                        ?>
                        <div class="col-md-4">
                            <?=($bHasPerm) ? ' <i class="fas fa-check"></i>' : ''?>
                            <?=$oField->label?>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </li>
    <?php
}
?>
</ul>

