<ul class="list-group">
<?php
# Get Partial Data
$aColumnsByTable = $this->aPartialData['aColumns'];
$aUserColumns = $this->aPartialData['aUserColumns'];

# Print List with all Modules and Columns
foreach(array_keys($aColumnsByTable) as $sTable) {
    $oTbl = $aColumnsByTable[$sTable]['oTable'];
    $aFields = $aColumnsByTable[$sTable]['aFields']; ?>
    <li class="list-group-item">
        <div class="row">
            <div class="col-md-4"><?=$oTbl->label?></div>
            <div class="col-md-8">
                <div class="row">
                    <?php foreach($aFields as $oField) {
                        //var_dump($oField);
                        $bHasPerm = false;

                        if(array_key_exists($oTbl->table_name,$aUserColumns)) {
                            if(array_key_exists($oField->fieldkey,$aUserColumns[$oTbl->table_name])) {
                                $bHasPerm = true;
                            }
                        }
                        ?>
                        <div class="col-md-4">
                            <?=($bHasPerm) ? ' <i class="fas fa-check"></i>' : ''?>
                            <?=$oField->label?>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </li>
    <?php
}
?>
</ul>
