<ul class="list-group">
<?php
# Get Partial Data
$aPermissonsByModules = $this->aPartialData['aPermissions'];
$aUserPermissions = $this->aPartialData['aUserPermissions'];

# Print List with all Modules and Permissions
foreach(array_keys($aPermissonsByModules) as $sModule) { ?>
    <li class="list-group-item">
        <div class="row">
            <div class="col-md-4">
                <?=$sModule?>
            </div>
            <div class="col-md-8">
                <?php foreach($aPermissonsByModules[$sModule] as $oPerm) {
                    $bHasPerm = false;
                    if(array_key_exists($sModule,$aUserPermissions)) {
                        if(array_key_exists($oPerm->permission_key,$aUserPermissions[$sModule])) {
                            $bHasPerm = true;
                        }
                    }
                    ?>
                    <?=($bHasPerm) ? ' <i class="fas fa-check"></i>' : ''?>
                    <?=$oPerm->label?>,
                <?php } ?>
            </div>
        </div>
    </li>
<?php
}
?>
</ul>
