<ul class="list-group">
<?php
# Get Partial Data
$aPermissonsByModules = $this->aPartialData['aPermissions'];
$aUserPermissions = $this->aPartialData['aUserPermissions'];

# Print List with all Modules and Permissions
foreach(array_keys($aPermissonsByModules) as $sModule) { ?>
    <li class="list-group-item">
        <div class="row">
            <div class="col-md-4">
                <?php
                $sBaseName = str_replace(['OnePlace-','Controller-','Controller'],['','',''],$sModule);
                $aParts = explode('-',$sBaseName);
                $sFullName = '';
                foreach($aParts as $sPart) {
                    $sFullName .= $this->translate($sPart).' - ';
                }
                echo substr($sFullName,0,strlen($sFullName)-strlen(' - '));
                ?>
            </div>
            <div class="col-md-8">
                <div class="row">
                    <?php foreach($aPermissonsByModules[$sModule] as $oPerm) {
                        $bHasPerm = false;
                        if (array_key_exists($sModule,$aUserPermissions)) {
                            if (array_key_exists($oPerm->permission_key,$aUserPermissions[$sModule])) {
                                $bHasPerm = true;
                            }
                        }
                        ?>
                        <div class="col-md-4">
                            <?=($bHasPerm) ? ' <i class="fas fa-check"></i>' : ''?>
                            <?=$oPerm->label?>,
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </li>
<?php
}
?>
</ul>
