<ul class="list-group">
<?php
# Get Partial Data
$aTabsByForm = $this->aPartialData['aTabs'];
$aUserTabs = [];

# Print List with all Modules and Tabs
foreach(array_keys($aTabsByForm) as $sTable) {
    $oForm = $aTabsByForm[$sTable]['oForm'];
    $aTabs = $aTabsByForm[$sTable]['aTabs']; ?>
    <li class="list-group-item">
        <div class="row">
            <div class="col-md-4"><?=$oForm->label?></div>
            <div class="col-md-8">
                <div class="row">
                    <?php foreach($aTabs as $oTab) {
                        //var_dump($oField);
                        $bHasPerm = false;

                        if (array_key_exists($oForm->form_key,$aUserTabs)) {
                            if (array_key_exists($oTab->Tab_ID,$aUserTabs[$oForm->form_key])) {
                                $bHasPerm = true;
                            }
                        }
                        ?>
                        <div class="col-md-4">
                            <input type="checkbox"<?=($bHasPerm) ? ' checked' : ''?> name="<?=$this->sFormName?>-tabs[]" value="<?=$oTab->Tab_ID?>_<?=$oForm->form_key?>" />
                            <?=$oTab->title?>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </li>
    <?php
}
?>
</ul>

