<ul class="list-group">
<?php
# Get Partial Data
$aTabsByForm = $this->aPartialData['aTabs'];
$aUserTabs = $this->aPartialData['aUserTabs'];

# Print List with all Modules and Tabs
foreach(array_keys($aTabsByForm) as $sTable) {
    $oForm = $aTabsByForm[$sTable]['oForm'];
    $aTabs = $aTabsByForm[$sTable]['aTabs']; ?>
    <li class="list-group-item">
        <div class="row">
            <div class="col-md-4">
                <?=$this->translate($oForm->label)?>
            </div>
            <div class="col-md-8">
                <div class="row">
                    <?php foreach($aTabs as $oTab) {
                        //var_dump($oField);
                        $bHasPerm = false;

                        if (array_key_exists($oForm->form_key,$aUserTabs)) {
                            if (array_key_exists($oTab->Tab_ID,$aUserTabs[$oForm->form_key])) {
                                $bHasPerm = true;
                            }
                        }
                        ?>
                        <div class="col-md-4">
                            <?=($bHasPerm) ? ' <i class="fas fa-check"></i>' : ''?>
                            <?=$this->translate($oTab->title)?>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </li>
    <?php
}
?>
</ul>
