<div class="card">
    <div class="card-header">
        <?=$this->translate('My Settings')?>
    </div>
    <div class="card-body" style="padding:0;">
        <ul class="list-group" style="margin:0; padding:0;">
            <li class="list-group-item">
                <a href="<?=$this->url('user',['action'=>'profile'])?>">
                    <?=$this->translate('Profile')?>
                </a>
            </li>
            <li class="list-group-item">
                <a href="<?=$this->url('user',['action'=>'settings'])?>">
                    <?=$this->translate('Settings')?>
                </a>
            </li>
        </ul>
    </div>
</div>