<form class="plc-login-form" action="" method="POST">
    <img src="/img/logo.png" style="max-height:120px; max-width:100%;"/>
    <br/>
    <hr/>
    <?php if (isset($sErrorMessage)) { ?>
        <div class="alert alert-danger">
            <?=$sErrorMessage?>
        </div>
    <?php } ?>
    <div class="md-form">
        <input type="text" id="plc_login_user" name="plc_login_user" value="" class="form-control" />
        <label for="plc_login_user"><?=$this->translate('Username or E-Mail')?></label>
    </div>

    <div class="md-form">
        <input type="password" name="plc_login_pass" value="" class="form-control" />
        <label for="plc_login_user"><?=$this->translate('Password')?></label>
        <small>
            <a href="<?=$this->url('forgot-pw')?>">
                <?=$this->translate('Forgot password?')?>
            </a>
        </small>
    </div>
    <div class="row">
        <div class="col-md-5">
            <button type="submit" value="Login" class="btn-floating btn btn-dark">
                <i class="fas fa-key ml-1"></i> <?=$this->translate('Sign in')?>
            </button>
        </div>
        <div class="col-md-4 py-2">
        </div>
        <div class="col-md-4">
        </div>
    </div>
</form>