<?php
use Application\Controller\CoreController;
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle(CoreController::$aGlobalSettings['app-title'].' - Login')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <!-- Bootstrap core CSS -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
        <!-- Material Design Bootstrap -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.10.1/css/mdb.min.css" rel="stylesheet">
        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
        ?>

        <!-- Scripts -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/jquery-3.4.1.min.js'))
        ?>
        <!-- Bootstrap tooltips -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
        <!-- Bootstrap core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <!-- MDB core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.10.1/js/mdb.min.js"></script>

    </head>
    <body style="padding:0; overflow:hidden;">
        <div class="container-fluid px-0 py-0">
            <div class="row">
                <div class="col-md-8" style="background-image: url('https://source.unsplash.com/random/featured/?nature') !important; background-position: center; background-repeat: no-repeat; background-size: cover;">

                </div>
                <div class="col-md-4" style="min-height: 100vh; padding:173px 55px 55px 55px; vertical-align: middle;">
                    <?php
                    /**
                     * Print Flashmessenger messages (alerts)
                     */
                    $flash = $this->flashMessenger();
                    $flash->setMessageOpenFormat('<div%s style="">
                                 <ul><li>')
                        ->setMessageSeparatorString('</li><li>')
                        ->setMessageCloseString('</li></ul></div>');
                    echo $flash->render('error',   ['alert', 'alert-dismissible', 'alert-danger', 'alert-plc']);
                    echo $flash->render('info',    ['alert', 'alert-dismissible', 'alert-info', 'alert-plc']);
                    echo $flash->render('default', ['alert', 'alert-dismissible', 'alert-info', 'alert-plc']);
                    echo $flash->render('warning', ['alert', 'alert-dismissible', 'alert-warning', 'alert-plc']);
                    echo $flash->render('success', ['alert', 'alert-dismissible', 'alert-success', 'alert-plc']);?>

                    <?= $this->content ?>
                    <hr>
                    <footer>
                        <p>&copy; <?= date('Y') ?>
                            <a href="<?=CoreController::$aGlobalSettings['app-url']?>" target="_blank">
                                <?=CoreController::$aGlobalSettings['app-copyright']?>
                            </a>. <?=$this->translate('All rights reserved')?>.</p>
                    </footer>
                </div>
            </div>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
